"""update floor model

Revision ID: 6127ac947f8a
Revises: 
Create Date: 2025-07-07 00:41:30.600778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6127ac947f8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floor_camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floor_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('faces', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('faces', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('faces', 'embedding',
               existing_type=sa.NullType(),
               nullable=False)
    op.add_column('floor', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('floor', sa.Column('floor_name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('floor_person_id_fkey'), 'floor', type_='foreignkey')
    op.drop_column('floor', 'security_cam_id')
    op.drop_column('floor', 'floorNum')
    op.drop_column('floor', 'person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floor', sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('floor', sa.Column('floorNum', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('floor', sa.Column('security_cam_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('floor_person_id_fkey'), 'floor', 'person', ['person_id'], ['id'])
    op.drop_column('floor', 'floor_name')
    op.drop_column('floor', 'id')
    op.alter_column('faces', 'embedding',
               existing_type=sa.NullType(),
               nullable=True)
    op.alter_column('faces', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('faces', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('floor_person')
    op.drop_table('floor_camera')
    op.drop_table('camera')
    # ### end Alembic commands ###
